[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["Dmitrii Fedorin"]

[dependencies]
bootloader = "0.10.12"
x86_64 = "0.14.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
