[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
volatile = "0.4.5"
x86_64 = "0.14.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
